include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_classes_with_only_static_members: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  
  errors:
    prefer_const_constructors: error
    curly_braces_in_flow_control_structures: error