name: flutter_module
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 2.0.4

dependencies:
  fluro: ^2.0.3    
  flutter:
    sdk: flutter
  flutter_hooks: ^0.16.0
  flutter_svg: ^0.21.0-nullsafety.1  
  font_awesome_flutter: ^9.0.0
  freezed_annotation: ^0.14.1
  hooks_riverpod: ^0.14.0+1
  logger: ^1.0.0
  responsive_framework: ^0.1.0
  shimmer: ^2.0.0-nullsafety.0
  supercharged: ^2.0.0
  
dev_dependencies:
  assets_scanner: ^2.0.0
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1+2
  json_serializable: ^4.1.0
  lint: ^1.5.3
  mocktail: ^0.1.1

flutter:  
  uses-material-design: true

  assets:
  - assets/icons/image_icons/rappipay/rappipay_icon.webp
  - assets/icons/image_icons/transaction_default/transaction_default_icon.webp
  - assets/icons/vector_icons/divide_icon.svg
  - assets/icons/vector_icons/more_dots_icon.svg
  - assets/icons/vector_icons/support_icon.svg
  - assets/icons/vector_icons/ticket_icon.svg

  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/poppins_regular.ttf
      - asset: assets/fonts/poppins_semi_bold.ttf
        weight: 600
  
  module:
    androidX: true
    androidPackage: com.rappipay_demo.flutter_module
    iosBundleIdentifier: com.rappipaydemo.flutterModule
