/// GENERATED BY assets_scanner. DO NOT MODIFY BY HAND.
/// See more detail on https://github.com/littleGnAl/assets-scanner.
class AppAsset {
  static const package = 'flutter_module';

  static const icons_image_icons_transaction_default_transaction_default_icon =
      'assets/icons/image_icons/transaction_default/transaction_default_icon.webp';

  static const icons_vector_icons_divide_icon =
      'assets/icons/vector_icons/divide_icon.svg';

  static const icons_vector_icons_more_dots_icon =
      'assets/icons/vector_icons/more_dots_icon.svg';

  static const icons_vector_icons_support_icon =
      'assets/icons/vector_icons/support_icon.svg';

  static const icons_vector_icons_ticket_icon =
      'assets/icons/vector_icons/ticket_icon.svg';

// ignore_for_file: always_put_control_body_on_new_line,always_specify_types,annotate_overrides,avoid_annotating_with_dynamic,avoid_as,avoid_catches_without_on_clauses,avoid_returning_this,lines_longer_than_80_chars,omit_local_variable_types,prefer_expression_function_bodies,sort_constructors_first,test_types_in_equals,unnecessary_const,unnecessary_new,public_member_api_docs,constant_identifier_names,prefer_double_quotes
}
